import Navbar from './Navbar';
import Head from 'next/head'
import Footer from './Footer';

const Layout = ({children}) => {
    return (  
        <>  
            <Head>
                <title>KKN BALASKRUMPRIK UNAIR 241</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/LOGO KKN.png" />
            </Head>
            <Navbar/>   
            {children}
            <Footer/>
        </>
    );
}
 
export default Layout;